import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import classes from './form-viewer.module.scss';
import form from '../../../exampleform.json';
import { FormFields } from '../../../components/FormFields';
import { FormFieldTemplate, FormTemplate } from '../../../types/builder.types';
import { Form, Formik, useFormik } from 'formik';
import { generateInitialValues } from '../../../utils/viewer/formik.utils';

const FormViewer: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  const formik = useFormik({
    initialValues: generateInitialValues(form as FormTemplate),
    onSubmit: (values) => {
      console.log('initial', generateInitialValues(form as FormTemplate));
      console.log('submit', values);

      // alert(JSON.stringify(values, null, 2));
    },
  });

  return (
    <div className={classes.container}>
      <Head>
        <title>{form.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Formik
        initialValues={generateInitialValues(form as FormTemplate)}
        onSubmit={(values) => {
          console.log('initial', generateInitialValues(form as FormTemplate));
          console.log('submit', values);

          // alert(JSON.stringify(values, null, 2));
        }}
      >
        <Form className={classes.form}>
          <header>
            <h1>{form.title}</h1>
          </header>
          <main>
            <FormFields
              formikProps={formik}
              fields={form.fields as FormFieldTemplate[]}
            />
          </main>
          <footer>
            <button type='submit'>submit</button>
          </footer>
        </Form>
      </Formik>
    </div>
  );
};

export default FormViewer;
