import { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import classes from './form-viewer.module.scss';
import form from '../../../exampleform.json';
import { FormFields } from '../../../components/FormFields';
import { FormFieldTemplate } from '../../../types/builder.types';

const FormViewer: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div className={classes.container}>
      <Head>
        <title>{form.title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <form action='submit' className={classes.form}>
        <header>
          <h1>{form.title}</h1>
        </header>
        <main>
          <FormFields fields={form.fields as FormFieldTemplate[]} />
        </main>
        <footer>
          <button type='submit'>submit</button>
        </footer>
      </form>
    </div>
  );
};

export default FormViewer;
