import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import classes from '../styles/Home.module.scss';

const placeholderForms = [1, 2, 3, 4, 5, 6];

const Home: NextPage = () => {
  return (
    <div className={classes.container}>
      <Head>
        <title>Forms</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={classes.main}>
        <nav className={classes.formNav}>
          <h1>Your Forms</h1>
          <input type='text' placeholder='Search...' />
          <button>New</button>
        </nav>
        <div className={classes.cardGrid}>
          {placeholderForms.map((form, idx) => (
            <div key={idx} className={classes.card}>
              <Link href={'/builder/' + form}>
                <a>{'form num' + form}</a>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
