import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { FormCard } from '../components/FormCard';
import { HubNav } from '../components/HubNav';
import classes from '../styles/Home.module.scss';
import { FormTemplate } from '../types/builder.types';

const Home: NextPage = () => {
  const [forms, setForms] = useState<FormTemplate[]>();
  const [query, setQuery] = useState('');

  useEffect(() => {
    const fetchForms = async () => {
      const res = await fetch('/api/templates');
      if (res.ok) {
        const json = await res.json();
        setForms(json.body);
      } else {
        setForms(undefined);
      }
    };
    fetchForms();
  }, []);

  const filteredForms = useMemo(() => {
    if (forms) {
      return forms.filter(({ title }) => title.includes(query));
    } else {
      return undefined;
    }
  }, [forms, query]);

  return (
    <div className={classes.container}>
      <Head>
        <title>Forms</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={classes.main}>
        <HubNav query={{ val: query, set: setQuery }} />
        <div className={classes.cardGrid}>{CardGrid(filteredForms)}</div>
      </main>
    </div>
  );
};

export default Home;

const CardGrid = (forms: FormTemplate[] | undefined) => {
  if (forms) {
    return forms.map((form, key) => <FormCard key={key} form={form} />);
  } else {
    return <span>loading...</span>;
  }
};
